### ISSUE TITLE
Add support to choose login column username/email/both

### ISSUE THREAD

**Issue by Omranic** [rinvex/fort#104]
Currently it's always both, we need to make it configurable

**Comment by noxify** [comment]
I think to extend the helper function is the best way to make it happen.
https://github.com/rinvex/fort/blob/master/src/Support/helpers.php#L28

If we check in the helper, what's defined in the config, we can decide which field should be used for the login. Also we don't have to change the controller logic for this.

**Comment by Omranic** [comment]
I guess we can't complain about the current way of implementation which works really fine in real world applications as per the feedback I got. We can keep it as it is right now, both username & email fields could be used alternatively for login for users' convenience..

**Comment by noxify** [comment]
maybe for a future feature we should check https://github.com/laravie/authen which allows us to define multiple fields for the login.
