### ISSUE TITLE
Rinvex Tenantable and Fort

### ISSUE THREAD

**Issue by rogerapras** [rinvex/fort#107]
How do I change Fort models to use the Tenantable package, since I need to use Trait

**Comment by Omranic** [comment]
Well, that's currently our scope, we're building something internally that utilizes both packages, and hopefully we'll either write a tutorial on how to, or maybe we can open source that new package so people can use it as a guidance and starting point to build their tenantable projects 👍

**Comment by Omranic** [comment]
It's now implemented and open-sourced in our [cortex/fort](https://github.com/rinvex/cortex-fort/) module [Example Here](https://github.com/rinvex/cortex-fort/blob/develop/src/Models/User.php), you can use it or see how it works there and implement it yourself in your project. For more details about how to use **Tenantable** features, please proceed to the documentation here: https://github.com/rinvex/tenants/tree/develop I'm sure it's now more detailed and expressive enough to explain all the basics needed 👌
