### ISSUE TITLE
Failed - validation

### ISSUE THREAD

**Issue by rogerapras** [rinvex/fort#113]
I have many problems with validation in code

$user = [
        'username' => 'admin',
        'email' => 'admin@rinvex.com',
        'email_verified' => true,
        'email_verified_at' => \Carbon::now(),
        'remember_token' => str_random(10),
        'password' => \Hash::make('123'),
        'active' => true,
];

 \Rinvex\Fort\Models\User::create($user);

Error returned "The given data failed to pass validation"

But if using the code works correctly

$user = [
        'username' => 'admin',
        'email' => 'admin@rinvex.com',
        'email_verified' => true,
        'email_verified_at' => \Carbon::now(),
        'remember_token' => str_random(10),
        'password' => \Hash::make('123'),
        'active' => true,
];

$temp = new  \Rinvex\Fort\Models\User();
foreach ($user as $key => $value) {
        $temp->$key = $value;
}
$temp->forceSave();

I can not find where it is generating this problem

**Comment by Omranic** [comment]
Should be fixed now, try to install latest revision from **develop** branch `composer require rinvex/fort:dev-develop` 👌
