### ISSUE TITLE
Your email already verified!

### ISSUE THREAD

**Issue by KhogaEslam** [rinvex/fort#126]
These exception happens in specific scenario 
steps:
1- register new user
2- chose login from top menu
3- enter already registered user login credentials   
this will throw exception 

> 

(1/1) ExceptionYour email already verified!
--
in EmailVerificationRequest.php (line 26)
at EmailVerificationRequest->authorize()
at call_user_func_array(array(object(EmailVerificationRequest), 'authorize'), array())in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php (line 87)
at BoundMethod::callBoundMethod(object(Application), array(object(EmailVerificationRequest), 'authorize'), object(Closure))in BoundMethod.php (line 31)
at BoundMethod::call(object(Application), array(object(EmailVerificationRequest), 'authorize'), array(), null)in Container.php (line 539)
at Container->call(array(object(EmailVerificationRequest), 'authorize'))in FormRequest.php (line 186)
at FormRequest->passesAuthorization()in ValidatesWhenResolvedTrait.php (line 21)
at FormRequest->validate()in FormRequestServiceProvider.php (line 31)
at FormRequestServiceProvider->Illuminate\Foundation\Providers\{closure}(object(EmailVerificationRequest), object(Application))in Container.php (line 1019)
at Container->fireCallbackArray(object(EmailVerificationRequest), array(object(Closure)))in Container.php (line 983)
at Container->fireAfterResolvingCallbacks('App\\Http\\Requests\\Frontend\\EmailVerificationRequest', object(EmailVerificationRequest))in Container.php (line 968)
at Container->fireResolvingCallbacks('App\\Http\\Requests\\Frontend\\EmailVerificationRequest', object(EmailVerificationRequest))in Container.php (line 627)
at Container->resolve('App\\Http\\Requests\\Frontend\\EmailVerificationRequest')in Container.php (line 575)
at Container->make('App\\Http\\Requests\\Frontend\\EmailVerificationRequest')in Application.php (line 728)
at Application->make('App\\Http\\Requests\\Frontend\\EmailVerificationRequest')in RouteDependencyResolverTrait.php (line 77)
at ControllerDispatcher->transformDependency(object(ReflectionParameter), array())in RouteDependencyResolverTrait.php (line 45)
at ControllerDispatcher->resolveMethodDependencies(array(), object(ReflectionMethod))in RouteDependencyResolverTrait.php (line 27)
at ControllerDispatcher->resolveClassMethodDependencies(array(), object(EmailVerificationController), 'request')in ControllerDispatcher.php (line 40)
at ControllerDispatcher->dispatch(object(Route), object(EmailVerificationController), 'request')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NoHttpCache.php (line 23)
at NoHttpCache->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateLastActivity.php (line 23)
at UpdateLastActivity->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Abilities.php (line 38)
at Abilities->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)
at require_once('/home/savvy/Code/testFort/public/index.php')in server.php (line 21)

**Comment by Omranic** [comment]
Confirmed! Thanks @KhogaEslam 👍 
Fix in progress..

**Comment by Omranic** [comment]
Fixed 👍
