### ISSUE TITLE
Creating default object from empty value || Class App\Http\Controllers\Frontend\EmailVerificationSendRequest does not exist

### ISSUE THREAD

**Issue by KhogaEslam** [rinvex/fort#127]
Request Email Verification
when entering a 'not verified email' and click on 'Request Email Verification' these exceptions appears.

The second exception happens whenever any exception that doesn't create user happens 
ex: if there is error in sending registration verification email, registration process stops so the second exception appeared.

> 1

(1/1) ReflectionExceptionClass App\Http\Controllers\Frontend\EmailVerificationSendRequest does not exist
--
in RouteSignatureParameters.php (line 25)
at ReflectionParameter->getClass()in RouteSignatureParameters.php (line 25)
at RouteSignatureParameters::Illuminate\Routing\{closure}(object(ReflectionParameter))
at array_filter(array(object(ReflectionParameter)), object(Closure))in RouteSignatureParameters.php (line 26)
at RouteSignatureParameters::fromAction(array('middleware' => array('web', 'web', 'nohttpcache'), 'uses' => 'App\\Http\\Controllers\\Frontend\\EmailVerificationController@send', 'as' => 'frontend.verification.email.send', 'namespace' => 'App\\Http\\Controllers\\Frontend', 'prefix' => 'verification/email', 'where' => array(), 'controller' => 'App\\Http\\Controllers\\Frontend\\EmailVerificationController@send'), 'Illuminate\\Database\\Eloquent\\Model')in Route.php (line 425)
at Route->signatureParameters('Illuminate\\Database\\Eloquent\\Model')in ImplicitRouteBinding.php (line 20)
at ImplicitRouteBinding::resolveForRoute(object(Application), object(Route))in Router.php (line 648)
at Router->substituteImplicitBindings(object(Route))in SubstituteBindings.php (line 39)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)
at require_once('/home/savvy/Code/testFort/public/index.php')in server.php (line 21)

> 

(1/1) ErrorExceptionCreating default object from empty value
--
in UpdateLastActivity.php (line 37)
at HandleExceptions->handleError(2, 'Creating default object from empty value', '/home/savvy/Code/testFort/vendor/rinvex/fort/src/Http/Middleware/UpdateLastActivity.php', 37, array('request' => object(Request), 'response' =>object(Response), 'user' => object(stdClass)))in UpdateLastActivity.php (line 37)
at UpdateLastActivity->terminate(object(Request), object(Response))in Kernel.php (line 218)
at Kernel->terminateMiddleware(object(Request), object(Response))in Kernel.php (line 189)
at Kernel->terminate(object(Request), object(Response))in index.php (line 58)
at require_once('/home/savvy/Code/testFort/public/index.php')in server.php (line 21)

**Comment by Omranic** [comment]
Should be fixed now, try to install latest revision from **develop** branch `composer require rinvex/fort:dev-develop` 👌
