### ISSUE TITLE
Type error: Argument 1 passed to Rinvex\Fort\Handlers\GenericHandler::authLockout() must be an instance of Illuminate\Http\Request, instance of Illuminate\Auth\Events\Lockout given

### ISSUE THREAD

**Issue by KhogaEslam** [rinvex/fort#130]
Exception when login attempts more than 5 times 

> 

(1/1) FatalThrowableErrorType error: Argument 1 passed to Rinvex\Fort\Handlers\GenericHandler::authLockout() must be an instance of Illuminate\Http\Request, instance of Illuminate\Auth\Events\Lockout given
--
in GenericHandler.php (line 56)
at GenericHandler->authLockout(object(Lockout))
at call_user_func_array(array(object(GenericHandler), 'authLockout'), array(object(Lockout)))in Dispatcher.php (line 367)
at Dispatcher->Illuminate\Events\{closure}('Illuminate\\Auth\\Events\\Lockout', array(object(Lockout)))in Dispatcher.php (line 199)
at Dispatcher->dispatch('Illuminate\\Auth\\Events\\Lockout')in helpers.php (line 446)
at event(object(Lockout))in ThrottlesLogins.php (line 81)
at SessionGuard->fireLockoutEvent(object(Request))in SessionGuard.php (line 96)
at SessionGuard->attempt(array('is_active' => true, 'username' => 'Fort', 'password' => 'IIvQSerN8wRy65Dsa'), false)in AuthenticationController.php (line 60)
at AuthenticationController->login(object(AuthenticationRequest))
at call_user_func_array(array(object(AuthenticationController), 'login'), array(object(AuthenticationRequest)))in Controller.php (line 55)
at Controller->callAction('login', array(object(AuthenticationRequest)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AuthenticationController), 'login')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in RedirectIfAuthenticated.php (line 29)
at RedirectIfAuthenticated->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NoHttpCache.php (line 23)
at NoHttpCache->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateLastActivity.php (line 23)
at UpdateLastActivity->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Abilities.php (line 38)
at Abilities->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)
at require_once('/home/savvy/Code/testFort/public/index.php')in server.php (line 21)

> 

(1/1) ErrorExceptionCreating default object from empty value
--
in UpdateLastActivity.php (line 37)
at HandleExceptions->handleError(2, 'Creating default object from empty value', '/home/savvy/Code/testFort/vendor/rinvex/fort/src/Http/Middleware/UpdateLastActivity.php', 37, array('request' => object(Request), 'response' =>object(Response), 'user' => object(stdClass)))in UpdateLastActivity.php (line 37)
at UpdateLastActivity->terminate(object(Request), object(Response))in Kernel.php (line 218)
at Kernel->terminateMiddleware(object(Request), object(Response))in Kernel.php (line 189)
at Kernel->terminate(object(Request), object(Response))in index.php (line 58)
at require_once('/home/savvy/Code/testFort/public/index.php')in server.php (line 21)

**Comment by Omranic** [comment]
Should be fixed now, try to install latest revision from **develop** branch `composer require rinvex/fort:dev-develop` 👌
