### ISSUE TITLE
[Feature] Allow users to self terminate their accounts

### ISSUE THREAD

**Issue by Omranic** [rinvex/fort#140]
With config option for admins to enable/disable this feature.

**Comment by noxify** [comment]
* Should we send a notification to the user, to confirm that the account was deleted?
* Should we create also a new event to make it extendable?

**Comment by Omranic** [comment]
We can require password confirmation, but no need for email pre-confirmation. An email after termination is just fine. Yes for the event 👍

**Comment by noxify** [comment]
A pre-confirmation via mail makes no sense.

The first point meant the confirmation email after terminating the account.

Password confirmation could be implemented via #84

**Comment by Omranic** [comment]
I've doubts about this feature currently, as the user is almost the center of the whole application & linked to almost every single record in the database with direct or indirect relationships, which makes me rethink the validity of this feature and if we need to implement it or now, specially when we still don't take advantage yet of soft deletes. Will close this for now..
