### ISSUE TITLE
Published resources cannot be overriden 

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#26]
I have published fort views to my app and they cannot be overridden as per Laravel documentation.
I wanted to change the blade layout template that Rinvex Fort is extending to another one and it seems to ignore the published views that I modify and still use the ones in the fort package instead of the published ones in `/resources/views/vendors/rinv...`.

What could be the problem?

I saw [this ](https://laracasts.com/discuss/channels/laravel/laravel-not-using-published-package-views?page=1) on laracast, but can't figure out if fort has a class alias that I am not seeing... Fort is using `loadViewFrom()` as expected, but still nothing is happening. My guess is that the directory to which it is being published to isn't correct.

This goes for the config file as well... the configuration isn't merging at all.

**Comment by Omranic** [comment]
Well, that means you didn't register the Fort service provider in your `app.php` config file within `$providers` array. Have you?
```php
Rinvex\Fort\Providers\FortServiceProvider::class,
```

**Comment by emahuni** [comment]
It's registered, fort is actually running and we love it. The change was in the software we are making. I used different layout files for different purposes and wanted authentication to use another layout file that's not `app.blade.php`. So when the change was done, it was expected that publishing the views would enable us to do an override of the default layout that was being used by fort, but nothing was working. We then updated fort for other reasons (backend implementation 👍) and still this same issue wasn't addressed, probably unknown. This was noticed even with configuration as well, we had to put it in `config/app.php` as a workaround earlier... Generally speaking all published fort resources, language, views and configuration (except for DB migrations), are not being picked up by Laravel. All other published packages are working well on doing that.

**Comment by Omranic** [comment]
Investigated right now, and seems to be true.. Just few minutes to make sure what's wrong & fix it in a quick update.. 👍

**Comment by emahuni** [comment]
Wow that was a good fix. Care to explain what was wrong?

Something else came up from that fix, minor I think. Let me create a separate issue for it.

**Comment by Omranic** [comment]
I know this is an old issue, and I maybe I don't remember what was the case, but from what I see in the fix there was a wrong views namespace. Hope this helps.
