### ISSUE TITLE
FatalThrowableError in Handler.php line 72: Class 'App\Exceptions\Lang' not found

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#27]
This error happens on original Laravel `Handler.php` file if the developer doesn't put it when installing the package (this is also IDE dependent to note that an import is missing). I think it should be stated in the documentation that the following line should be added on top of the `Handler.php` file:

```php
	use Illuminate\Support\Facades\Lang;
```

**Comment by Omranic** [comment]
Yup, current docs are completely obsolete as the package has been refactored multiple times, and things changed on the way up to current state, this is our main concern now is to write a decent docs before tagging the package as stable for usage.. Thanks @emahuni for the report 👍
