### ISSUE TITLE
Add question and answer password recovery

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#30]
It's of great convenience to add an option to make password recovery work offline without any email or phone as recovery option. Implementing this can help with offline, local-only applications with offline functionality as their requirement. 
#### Implementation options:
- User can be asked to choose/create recovery questions maybe two or three that should be answered properly before the recovery page is presented to the user.
- User can actually provide clues to help them remember the password when offline.

**Comment by Omranic** [comment]
Well even that's a nice idea, what about the emergency TOTP passwords?

Currently we've something similar already implemented. If the user activated Two-Factor Authentication on his account, he will get 10 One-TIme-Passwords for emergency situations like this, which is usable for the same purpose as your scenario.. What do you think?

**Comment by Omranic** [comment]
TwoFactor authentication already implemented and one of the core features right now, it could be utilized for such thing if I understand your scenario correctly.
