### ISSUE TITLE
New Layout.blade.php file assuming styles, fonts, and script sources (breaks on other configs)

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#32]
Ok the fix to:
`Published resources cannot be overriden #26 
 Closed 
emahuni opened this Issue 3 days ago · 3 comments `

was brilliant work 👍 , however it spawned a simple deal-breaker to would-be package users.

The style, fonts and script sources are just too assumed and too dependent on the referenced code-base.
Output on my setup:

![image](https://cloud.githubusercontent.com/assets/7290508/19235727/cb233e5e-8ef3-11e6-93c8-27b73ddd7034.png)

I think the default Laravel Scafolding styles, scripts and fonts should be used... maybe just take the default scaffolding and use that in the default layout file and explain to user to publish it and customize it in the layout file. I don't even use any of the assumed structure nor sources in my configuration, which means mostly to other users it may break as well. 

Therefore just using the default scaffolding can cover those tracks, and if the user had customized it means they'll know exactly what's going on and a bit of explanation on the layout page maybe after yielding of content into common.layout file would do justice to those that see the unstyled, un-jqueried and un-bootstraped page and don't understand what's going on.

**Comment by Omranic** [comment]
Thanks for the explanation and for the appreciated PR #33 👍 (merged) 
I still consider this package away from optimum, and even after tagging a stable release it will still require a lot of efforts for making it a reliable, solid, and efficient one-stop defacto auth solution for the whole Laravel ecosystem, so please keep using, reporting, and most appreciated sending PRs 😄 @emahuni
