### ISSUE TITLE
SSO Login

### ISSUE THREAD

**Issue by mits87** [rinvex/fort#38]
Hello,

I have one question. Are you thinking about implement a Single Sign-On strategy (SAML2) as alternative to your package? IMHO is great business feature. What do you think?

Best Regards
Peter

**Comment by Omranic** [comment]
Hi @mits87 
Yup, that's already planned 😉 #14 
Both will be available, an open-source package & a SAAS service, hopefully soon..
Feel free to re-open this issue if you've further questions 👍
