### ISSUE TITLE
Two Factor Auth

### ISSUE THREAD

**Issue by noxify** [rinvex/fort#43]
Hi,

everything is working fine so far.

I created a new user.
* welcome email sent
* activation email sent 
* activation is done for the created user

* Logged in without Two Factor
* In the User Settings
** Filled First Name and Last Name
** Set my phone number ( schema: +491234567890
** Set Country to "Germany" --> DB: "de"
* Saved Profile
* enabled Two Factor via Google Authenticator
* Checked the DB --> field "two_factor" is filled
* Logout
* Tried to login with the user credentials

Expected: View to enter the two factor code
Current: Login view with "You have to login first"

Based on what I can see via Debugbar

* POST login was successful
* tries to run "/verification/phone/verify"
* redirect to "/login"

I have added some debug statements, the result for `$result` inside `processLogin` is `null`.

Is it not implemented (yet - like the social auth) or did I forgot something?

**Comment by noxify** [comment]
got it!

in `config/rinvex.fort.php` I have to activate both options in providers

```php
        'providers' => [

            'totp',
            'phone',

        ],

```

**Comment by Omranic** [comment]
@noxify I'm really sorry for lack of appropriate support for this package, the thing is we were not going to release it until it's ready, but we thought maybe we could develop it in public. Anyway we've wild plans for this package, and we're eager to make it Laravel's Authentication/Authorization flagship, it's just a matter of time 😄

**Comment by noxify** [comment]
Hi,

no problem - currently it works as expected ( with some limitations, that's ok for me ).

I have updated the `/config/rinvex.fort.php` with the following

```php
        'authy' => [
        	
        	'enabled'   => false,

            'mode' => env('AUTHY_MODE', 'live'),

            'keys' => [
                'live'    => env('AUTHY_KEYS_LIVE', ''),
                'sandbox' => env('AUTHY_KEYS_SANDBOX', ''),
            ],

        ],
```

the `enabled` flag will be used in the settings view to enable/disable the "phone verification" stuff.

But thanks for the feedback :)
