### ISSUE TITLE
[Known Issue] Seeders aren't working correctly with pgsql and sqlite

### ISSUE THREAD

**Issue by noxify** [rinvex/fort#58]
Hi,

with the current implementation to truncate the tables before starting the seeds, it works only with `mysql`.

I found the following:
https://espadav8.co.uk/2015/03/04/laravel-database-seeding-with-postgresql/

I will test it now with `postgres`and `mysql`.

If everything is working, i will post an PR.

If anyone has another solution or an idea to solve the problem with `postgres`, please let me know.

**Comment by noxify** [comment]
If anyone else has this problem, the current Workaround is:

Create your own Seeds and use the Code from PR #59.
Run then `php artisan db:seed` and everything is working fine.

**Comment by Omranic** [comment]
Seems to be out of focus for the current and next quarter honestly, so will be closed for now. Seeds and migrations could be published and customized easily if needed as a way around anyway 🙂
