### ISSUE TITLE
Wiki Installation correction

### ISSUE THREAD

**Issue by noxify** [rinvex/fort#64]
Hi,

there is a wrong command in the wiki ( https://github.com/rinvex/fort/wiki/1)-Installation )

Current:

```
php artisan db:seed --class="\Rinvex\Fort\Seeds\DatabaseSeeder"
```

Correction:

```
php artisan db:seed --class=\Rinvex\Fort\Seeds\DatabaseSeeder
```

**Comment by Omranic** [comment]
What's wrong with the current command?
It's always better to wrap string arguments inside quotes..

**Comment by noxify** [comment]
Not sure if it's just a problem on my side, but even when I try to run "stringified" version, the result is the following:

```
> php /Applications/MAMP/htdocs/rinvex_fort/artisan db:seed --class="\Rinvex\Fort\Seeds\DatabaseSeeder"
                                                         
  [ReflectionException]                                     
  Class "\Rinvex\Fort\Seeds\DatabaseSeeder" does not exist  
```

* PHP: 7.1.0
* MySQL: 5.6.34
* Laravel: 5.4
* Fort: dev-develop
* Composer
** minimum-stability: dev

**Comment by noxify** [comment]
Seems to be an PHPStorm Command Line Tools problem only.

If I run

```
php artisan db:seed --class="\Rinvex\Fort\Seeds\DatabaseSeeder"
```

from terminal directly, it works.

**Comment by Omranic** [comment]
Anyway tried on PHPStorm and it worked as expected.
- PHPStorm 2016.3
- macOS Sierra
- Laravel 5.4

**Comment by noxify** [comment]
Hmm.. then maybe something is wrong in my OSX :D 
Time for a new one :)
