### ISSUE TITLE
Missing Methods in GenericHandler

### ISSUE THREAD

**Issue by noxify** [rinvex/fort#76]
Hi,

while testing the registration, I found some missing methods inside the `GenericHandler`.

* authUnverified
* twoFactorRequired
* registerStart
* registerSocialStart
* passwordResetStart
* passwordResetSuccess
* emailVerificationStart

In my case, the error message is/was:

```
call_user_func_array() expects parameter 1 to be a valid callback, class 'Rinvex\Fort\Handlers\GenericHandler' does not have a method 'registerStart'
```

**Comment by Omranic** [comment]
Fixed ba253f2
