### ISSUE TITLE
FatalThrowableError in AccountController.php line 163: Call to a member function getTwoFactor() on null

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#8]
This happens whenever I tried to access routes with the following line for two factor authentication in `vendor/rinvex/fort/src/Http/Controllers/AccountController.php`:

`$this->currentUser ... ;`

for routes such as 

/account/page
or
/account/twofactor/totp/enable

I inserted code:
`use Illuminate\Support\Facades\Auth; // (at top of coz)`
then i inserted:
`$this->currentUser = Auth::guard($this->getGuard())->user() ?: Auth::guard($this->getGuard())->attemptUser();`
just below:
`parent::__construct();`
in the class' constructor.

and it worked, though I am not sure of the code involved between where it was supposed to fetch the user and where i just fetched it. It seems like the current user or attempt user wasn't available on construction in `vendor/rinvex/fort/src/Http/Controllers/FoundationController.php` where it  (_`$this->currentUser`_) was supposed to be assigned.

I am using laravel 5.3

**Comment by Omranic** [comment]
Confirmed: https://laravel-news.com/2016/08/controller-construct-session-changes-in-laravel-5-3/
A fix is currently in development, and a fix will be issued soon 👍

**Comment by emahuni** [comment]
Ok. Eeesh sorry for the edits. I was actually about edit one more time :+1:

I actually ended up putting the following code in each method in the class `vendor/rinvex/fort/src/Http/Controllers/AccountController.php`:

```
$this->currentUser = Auth::guard($this->getGuard())->user() ?: Auth::guard($this->getGuard())->attemptUser();
	    view()->share(['currentUser' => $this->currentUser]);
```

and removed the constructor edits i had done earlier.

It also seems like another controller is using the same code.

`vendor/rinvex/fort/src/Http/Controllers/VerificationController.php`

I am not sure if it needs editing.

**Comment by Omranic** [comment]
Yeah, good quick fix, this is gonna b fixed radically mostly through the session guard itself without away from controllers, will keep this issue opened until fixed 👌

**Comment by emahuni** [comment]
keep an eye for $currentUser in views, it's wrecking havok.

`Trying to get property of non-object (View: ...\vendor\rinvex\fort\resources\views\account\sessions.blade.php)`

it's not being shared properly as expected from `view()->share(['currentUser' => $this->currentUser]);`

**Comment by emahuni** [comment]
I think $currentUser should be available to every view. It should be shared using service provider as mentioned in Laravel Docs under views. Can't it be done just like it was being implemented under original Laravel scafolding. Auth::User()->name;

**Comment by Omranic** [comment]
Sure, I like that idea & will go by Laravel docs recommendations. If you believe you've a solid implementation in mind, feel free to submit a PR 🙂👍

**Comment by emahuni** [comment]
To fix the current user issue on views I've created a view composer that attaches current user to all views in the app and not in the fort package using Laravel recommendations of view composers... It uses about three lines from this code and works great to provide views with currentUser variable. Let me submit a PR for that.
