### ISSUE TITLE
Laravel 5.4 install error

### ISSUE THREAD

**Issue by DeeJaVu** [rinvex/fort#83]
im getting this error when running composer require rinvex/fort

```
Problem 1
    - Installation request for rinvex/fort ^0.0.2 -> satisfiable by rinvex/fort[v0.0.2].
    - rinvex/fort v0.0.2 requires rinvex/repository dev-develop -> satisfiable by rinvex/repository[dev-develop] but these conflict with your requirements or minimum-stability.
```

**Comment by noxify** [comment]
@DeeJaVu - You have to use the `develop` branch.

**Comment by DeeJaVu** [comment]
@noxify still error 

Problem 1
    - Installation request for rinvex/fort dev-develop -> satisfiable by rinvex/fort[dev-develop].
    - rinvex/fort dev-develop requires rinvex/country dev-develop -> satisfiable by rinvex/country[dev-develop] but these conflict with your requirements or minimum-stability.

my laravel version is 5.4.9
php version is 7.0.13

**Comment by noxify** [comment]
Did you change/add the `minimum-stability` to `dev` in your `composer.json`?

```
    "minimum-stability": "dev"
```

**Comment by DeeJaVu** [comment]
hmm it works now thx :)

**Comment by noxify** [comment]
Currently there is no stable release, so this is the only solution currently to use it.

But good to hear, that it's working now.

Have fun :)
