### ISSUE TITLE
Password not encryped when using my own user model

### ISSUE THREAD

**Issue by noxify** [rinvex/fort#98]
Hi,

I updated my app to the latest develop branch.

I have my own user model which is extending the rinvex user model.
Everything seems ok and the seeds are running without any errors.

But while checking the user table, I realized that the passwords are not encrypted from the event handler `Rinvex\Fort\Handlers\UserHandler`.

If I change the used model in the seed to the Rinvex User Model the password is encrypted as expected.

User Handling or a known feature ;) ?

**Comment by noxify** [comment]
Solved :)

app\Providers\EventServiceProvider.php
```
<?php

namespace App\Providers;

use App\Models\User;
use Rinvex\Fort\Handlers\UserHandler;
use Illuminate\Support\Facades\Event;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
	    User::observe(UserHandler::class);
    }
}
```

**Comment by Omranic** [comment]
OMG! This is terrible. I'm really sorry about this issue.
I believe passwords must be hashed all time without any probability of such leakage even for custom models. Just reverted back to the more strict and way of auto hashing through mutators. It's now enforced no matter what: dd4a6d908142a7a5d620914b2c5baca4a58ecf76

**Comment by noxify** [comment]
works as expected - thanks!
